### ISSUE TITLE
Set python as defualt for py files

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fife-windows-sdk#14]
We need to set .py files that they get opened by default with our python. When our python is selected to be installed.

**Comment by jakoch** [comment]
Ok. 

- [x] register file type handler for the extension .py, which uses `fifesdk\python\python.exe`.

Notes for myself:

- https://docs.python.org/3/faq/windows.html#how-do-i-make-python-scripts-executable
- http://www.jrsoftware.org/isfaq.php#assoc

**Check file association with**
```
C:\>assoc .py
.py=Python.File

C:\>ftype Python.File
Python.File="c:\fifesdk\python\python.exe" "%1" %*
```
**or**
```
assoc | findstr -i python
ftype | findstr -i python
```

and, of course,  double-clicking a .py file should execute the file using the given python executable.

**Comment by jakoch** [comment]
- [x] needs testing

**Comment by LinuxDonald** [comment]
Tested an it works for me 👍

**Comment by jakoch** [comment]
Thanks for testing!! 👍
