### ISSUE TITLE
Adding PyYaml to the SDK?

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fife-windows-sdk#16]
Maybe we should add PyYaml to the SDK because UH needs it.
When i want to install it with the win installer it dont find python... Same bullshit installer as the old fife installer before we used the .msi one...
Or should this be done in the UH installer?

**Comment by jakoch** [comment]
> Or should this be done in the UH installer?

Good question. I'm not sure, if this is a direct dependency of the FifeSDK. 
One projects works with YAML, while others prefer working with XML or JSON.
But when we add it to the SDK, it will reduce the complexity for game installers.
So.. let's throw a coin...

**Comment by LinuxDonald** [comment]
Yeah but PyYaml would not really make the sdk bigger in size and we could it set as not default installing. Make an info text with: Needed for Unknown-Horizons?

Or we only add direkt deps as Cegui for example?

**Comment by jakoch** [comment]
Let's add direct dependencies or build tools only. Would you agree?
That would mean that PyYAML goes into the UH installer. 

I agree on CEGUI. That's an optional dependency of fife, so we should ship it with the FifeSDK.
That enables a user to simply flip a cmake switch (configuration option) and work with CeGUI.

**Comment by LinuxDonald** [comment]
Yeah its okay :)
