### ISSUE TITLE
add appveyor status badge to readme

### ISSUE THREAD

**Issue by jakoch** [fifengine/fife-windows-sdk#2]
See https://www.appveyor.com/docs/status-badges/

I've tried adding it in a similar way to what i did on the fifengine repo:

` [![Appveyor Build status](https://ci.appveyor.com/api/projects/status/github/fifengine/fifengine?branch=master&svg=true)](https://ci.appveyor.com/project/LinuxDonald/fifengine)`

But i couldn't find a  working image URL:

`https://ci.appveyor.com/api/projects/status/github/fifengine/fife-windows-sdk?branch=master&svg=true` 
![status badge](https://ci.appveyor.com/api/projects/status/github/fifengine/fife-windows-sdk?branch=master&svg=true)

**Comment by LinuxDonald** [comment]
For current status: [![Build status](https://ci.appveyor.com/api/projects/status/x74i9a32q9x6kiug?svg=true)](https://ci.appveyor.com/project/LinuxDonald/fife-windows-sdk)

`[![Build status](https://ci.appveyor.com/api/projects/status/x74i9a32q9x6kiug?svg=true)](https://ci.appveyor.com/project/LinuxDonald/fife-windows-sdk)`

For master: [![Build status](https://ci.appveyor.com/api/projects/status/x74i9a32q9x6kiug/branch/master?svg=true)](https://ci.appveyor.com/project/LinuxDonald/fife-windows-sdk/branch/master)

`[![Build status](https://ci.appveyor.com/api/projects/status/x74i9a32q9x6kiug/branch/master?svg=true)](https://ci.appveyor.com/project/LinuxDonald/fife-windows-sdk/branch/master)`

**Comment by jakoch** [comment]
Thank you!
