### ISSUE TITLE
The SDK dont set the PYTHON and FIFE PATH

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fife-windows-sdk#6]
We should replace the the python from appveyor with the official python Installer. Because without the official installer fife installer dont find the installed python.

https://www.python.org/downloads/

**Comment by jakoch** [comment]
I don't think that this is needed.

For example, when 
- installing the SDK into `d:\fifesdk`
- Python will be installed into `d:\fifesdk\python`

When the MSI installer (for Python27 libfife) is executed by the SDK installer it 
asks for the install location and the user can simply provide it, see:
![alt-python-dir](https://cloud.githubusercontent.com/assets/85608/20856906/02eb1d0e-b91d-11e6-98a0-49e78487ac5c.png)

After that libfife is correctly installed into `D:\fifesdk\python\Lib\site-packages\fife`

----

💡  Idea : We might try passing the Python path to the MSI installer when it is called. 
I'm sure the MSI accepts CLI parameters, but i'm not sure how to set the Python path exactly.
To find out the property for the python path, we could run the MSI standalone with logging enabled to see the Properties names (by examing lines in `install.log` with Property(S) or Property(C): `msiexec /L* D:\install.log`).

**Comment by LinuxDonald** [comment]
I forgot to write why i asked about this change. The Problem was:

1. installed sdk
2. installed fife
3. get UH and it dont found python and dont found fife.
4. installed offical python fife installer found python by it self UH found python but not fife
5. added "C:\Python27\Lib\site-packages\fife" to path UH runs fife (needed extra dep. python yaml)

**Comment by jakoch** [comment]
That's probably a problem with the UH installer itself, then... 

I think it expects Python at `C:\Python27` and doesn't take other Python versions (3.x) or custom install locations of Python into account. 

This file needs to be adjusted for Python3 support i think:
- https://github.com/unknown-horizons/unknown-horizons/blob/dcbdef20b771920b506bbb7fd7860d38163f25de/development/create_windows_installer.sh

- When i look at the installer template, then there is INSTDIR = https://github.com/unknown-horizons/unknown-horizons/blob/dcbdef20b771920b506bbb7fd7860d38163f25de/development/nsi.template#L65
This would mean that UH finds Python, when it is installed into the same folder: `fifesdk`, which doesn't make much sense, because you want UH in it's own folder. Guess, the UH installer needs a dialog to select the Python location.

**Comment by LinuxDonald** [comment]
I have taken UH from git without installer. Problem is to when you type python on the CMD it dont find it. Because its not in the PATH Variable.

**Comment by LinuxDonald** [comment]
And because of the UH installer im thinking about to change it to inno setup too.

**Comment by jakoch** [comment]
> Problem is to when you type python on the CMD it dont find it

Ok, then we are back at "set PATH to Python during the installation of FifeSDK", right?

> And because of the UH installer im thinking about to change it to inno setup too.

Not sure if rewriting the UH installer is really needed, because NSIS und INNO are pretty similar. 
But, i wish i had more time to help you with that.. :(

**Comment by LinuxDonald** [comment]
Yeah we must find an way how to set python to path. Maybe i will found something.
And because of switching to Inno i think it would be easier to maintain because then fife and UH use the same installer. And we could maybe fix easier bugs then too in both installers. And i dont know how to write the NSIS installer for appveyor.

About fife i will wait some time what prock say about the open pr then retag fife to 0.4.0 and release it after it i hope we have done fife sdk. That i can start with UH.

**Comment by LinuxDonald** [comment]
I found something but i dont understand it:

http://stackoverflow.com/questions/3304463/how-do-i-modify-the-path-environment-variable-when-running-an-inno-setup-install
http://www.jrsoftware.org/isfaq.php#env

And i found how we can set Installer Icon :)

http://www.jrsoftware.org/isfaq.php#setupicon

**Comment by jakoch** [comment]
> And i found how we can set Installer Icon

Every detail counts, once the big issues are resolved.
By the way: the installer images have a transparency problem.

----

Ok, the StackOverflow solution makes sense.
They set the PATH var by adding it as Registry Key, which looks scary at first, but works.
The base for the solution is this snippet:
```
[Registry]
; set Python PATH
Root: HKCU; Subkey: "Environment"; ValueType:string; ValueName:"PATH"; ValueData:"{olddata};{app}\Python"; Flags: preservestringtype

[Setup]
; Tell Windows Explorer to reload the environment
ChangesEnvironment=yes
```
Here the old PATH data is appended with `{app}\Python`.

Two problems:
- The fist problem is that you don't know, if this path is already on the PATH.
  That's why the SO answer includes `function NeedsAddPath` in the `[Code]` section.
- The second problem is that you have to make sure that the added PATH is removed properly during uninstallation.

**Comment by LinuxDonald** [comment]
Maybe only set PATH when the user installs the python version forum our sdk? When that is makeable with the installer?

And about removing this would be need testing :)

**Comment by LinuxDonald** [comment]
Because of transparency maybe we must use PNG instand of BMP?

And im thinking about to make an fife linux release only. And add the Windows Version later? Because i think we will dont fix all problems this year.

**Comment by jakoch** [comment]
> Because of transparency maybe we must use PNG instand of BMP?

PNG isn't supported, only BMP. It might be an alpha channel issue,
http://www.jrsoftware.org/ishelp/index.php?topic=setup_wizardimagefile

> And about removing this would be need testing :)

We need clones or robots  🤖 too much work, not enough time 🕐 
And that means: test the bare minimum and let the users report the bugs. Like with all bad software.
By the way: there is PyAutoGui, which allows to write test scripts for GUI applications, which is awesome :)
- https://www.youtube.com/watch?v=dZLyfbSQPXI
- https://pyautogui.readthedocs.io/en/latest/

**Comment by LinuxDonald** [comment]
Yeah more time would be very nice :( Yeah reporting Bugs is good we will never find all problems together :D I will later take an look on the bmp files and see what GIMP have settings for the format.

**Comment by LinuxDonald** [comment]
I found something more that could help here: http://stackoverflow.com/questions/16157700/python-distribute-module-using-inno-setup

I Searched how i can install python moduls with inno setup and found this but i think it could help to with our problem?

**Comment by jakoch** [comment]
- [ ] path to python
- [ ] path to installed libfife (= python site-packages folder, because DLLs)

**Comment by LinuxDonald** [comment]
```
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
  ParamExpanded: string;
begin
  //expand the setup constants like {app} from Param
  ParamExpanded := ExpandConstant(Param);
  if not RegQueryStringValue(HKEY_LOCAL_MACHINE,
    'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
    'Path', OrigPath)
  then begin
    Result := True;
    exit;
  end;
  // look for the path with leading and trailing semicolon and with or without \ ending
  // Pos() returns 0 if not found
  Result := Pos(';' + UpperCase(ParamExpanded) + ';', ';' + UpperCase(OrigPath) + ';') = 0;  
  if Result = True then
     Result := Pos(';' + UpperCase(ParamExpanded) + '\;', ';' + UpperCase(OrigPath) + ';') = 0; 
end;
```

@jakoch can we add this 1:1 into our code?

**Comment by LinuxDonald** [comment]
or maybe this: http://legroom.net/software/modpath

**Comment by jakoch** [comment]
- [x] added env path helper for innosetup
- [x] added path to python
- [x] added path to installed libfife (= python site-packages folder, because DLLs)

**Status**:
- [ ] needs testing

**Comment by LinuxDonald** [comment]
Appveyor Build failed 
[log.txt](https://github.com/fifengine/fife-windows-sdk/files/669479/log.txt)

**Comment by jakoch** [comment]
The build succeeded after a couple of fixes: [FifeSDK-0.0.44-Setup-VC14-x86.exe](https://ci.appveyor.com/api/buildjobs/nr6b4xayc5s1l3s1/artifacts/FifeSDK-0.0.44-Setup-VC14-x86.exe)

**Comment by LinuxDonald** [comment]
It dont set any paths :(

EDIT:
It only set local path but not system path. We need to change that. But the bigger problem is there is no python27.dll

![pythondllerror](https://cloud.githubusercontent.com/assets/1757651/21466962/95c15430-c9db-11e6-8272-b9a0af176e27.jpg)

**Comment by LinuxDonald** [comment]
Maybe we should add offical Python installers into the sdk and for cmake too?

**Comment by jakoch** [comment]
The missing python27.dll is a new issue. Seems it's not in the Python folder, but in the Windows folder.
We need to copy it into the Python folder first, then the installer includes it during packaging.

----
Here is a new installer for testing the following things:
  - installation of libfife into python folder
  - add paths
  - uninstallation of FifeSDK triggers uninstallation of libfife python module
  - uninstallation removes paths
  - Python27.dll is installed into the Python folder

Note: i couldn't locate `Python35.dll` on Appveyor, it's not at `C:\Windows\SysWOW64\python35.dll`


[FifeSDK-0.0.52-Setup-VC14-x86.exe](https://ci.appveyor.com/api/buildjobs/wplti28r61eoxml3/artifacts/FifeSDK-0.0.52-Setup-VC14-x86.exe)

**Comment by LinuxDonald** [comment]
Tested now: FifeSDK-0.0.52-Setup-VC14-x86
it finds python but .py files must be set that it get open with python one time.
Uninstall works but PATH dont get removed.

**Comment by LinuxDonald** [comment]
You can remove this line: +;Source: "C:\Windows\SysWOW64\python35.dll";     DestDir: "{app}\python";                Flags: recursesubdirs ignoreversion; Components: "Python\py35"

Python3 dont have any problems:
![py3](https://cloud.githubusercontent.com/assets/1757651/21483113/85f96242-cb7d-11e6-93d7-a417b8ce7b1d.jpg)

**Comment by LinuxDonald** [comment]
About PATH Delete i found this:
http://stackoverflow.com/questions/26762668/inno-setup-how-to-uninstall-registry-value

and
http://stackoverflow.com/questions/35410421/inno-setup-remove-path-from-path-environment-variable-while-uninstalling-a-pro

but the first one is very short and when it works it would be cool.

**Comment by LinuxDonald** [comment]
Flags: uninsdeletekey is not an good idea it have delete the complete entry in my reg.....

**Comment by jakoch** [comment]
:(

We are already using the second solution, see https://github.com/fifengine/fife-windows-sdk/blob/master/installer/includes/envpath.iss#L45

I've no clue, why the path is not removed, when using that function.
Maybe the PATH is written, but doesn't stick. This solution refreshes the environment after the path modification: http://stackoverflow.com/a/37840446/1163786  
I guess we need to run the uninstaller with logging enabled to find out what's going on.

**Comment by LinuxDonald** [comment]
Your last git changes dont help. Should i create an bug report at inno setup? maybe they can help us?

**Comment by jakoch** [comment]
Contacting the InnoSetup team isn't needed. Btw. they only give support via mailinglist... old age 
and i would always ask on StackOverflow first for getting a faster response. 

Anyway... i'm still trying to track the issue down. 
For debugging the uninstaller: `unins000 /LOG=c:\fife_uninst.log`
I think we have registry key mismatch:
the installer writes to the `user env path`, but the uninstaller tries to remove from the `system env path`

**Comment by LinuxDonald** [comment]
Can't we maybe set the system path then instand of user?

**Comment by jakoch** [comment]
I've justed added additonal functions to `envpath.iss ` to support env path modification on both of the registry keys `HKEY_Current_User` and `HKEY_Local_Machine`. 
For now the modified env path is `HKEY_Current_User` - if that works, we could still decide to modify `HKEY_Local_Machine`.

**Comment by jakoch** [comment]
Finally, it's working... 😄 

```
2016-12-27 17:42:10.250   Prepare to remove from Old PATH [%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\server-086\bin\mariadb\bin;c:\fifesdk\python;c:\fifesdk\python\Lib\site-packages\fife]
2016-12-27 17:42:10.251   Path [c:\fifesdk\python\Lib\site-packages\fife] removed from PATH => [%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\server-086\bin\mariadb\bin;c:\fifesdk\python]
2016-12-27 17:42:10.251   PATH written
2016-12-27 17:42:10.251   Prepare to remove from Old PATH [%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\server-086\bin\mariadb\bin;c:\fifesdk\python]
2016-12-27 17:42:10.251   Path [c:\fifesdk\python] removed from PATH => [%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\server-086\bin\mariadb\bin]
2016-12-27 17:42:10.251   PATH written
```

**Comment by LinuxDonald** [comment]
I can confirm that too :)
You are the best jakoch :) I will never let you leave the fife team :P 👍 🥇

**Comment by LinuxDonald** [comment]
I close this here and created an new issue for the default python problem: #14
