### ISSUE TITLE
Trigger uninstall of fife installer.

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fife-windows-sdk#7]
We need to fix that when fife sdk get uninstalled that it uninstalls too fife-engine.

**Comment by jakoch** [comment]
- [x] insert correct filepath to uninstaller executable
- [x] test

**Comment by jakoch** [comment]
The uninstallation of libfife is triggered during the uninstallation of the SDK, see
https://github.com/fifengine/fife-windows-sdk/blob/master/installer/fife-sdk.iss#L126
It's done by storing the libfife msi file in the fifesdk folder and then executing it via `msiexec /x`.

**Comment by LinuxDonald** [comment]
Tested and it works :) Great work jakoch 👍
